### DISCUSSION TITLE
sap_swpm - Pseudo Idempotency Ideas

### DISCUSSION THREAD

**Discussion by berndfinger** [sap-linuxlab/community.sap_install#1005] [Ideas]
https://github.com/sap-linuxlab/community.sap_install/issues/730 suggested to make sap_swpm (pseudo idempotent), and https://github.com/sap-linuxlab/community.sap_install/pull/1003 was a first attempt to do so.

The discussion in the PR revealed that there is more to consider.

I think we need to take into account the following:

1. Desired SAP instance installation
- An attempt is made to install only one SAP instance on one target host (e.g. using `sap_swpm_product_catalog_id` `NW_DI:S4HANA2023.FNDN.HDB.PD`
- An attempt is made to install more than one SAP instance on one target host (e.g. using `sap_swpm_product_catalog_id` `NW_ABAP_OneHost:S4HANA2023.FNDN.HDB.ABAP`

2. SAP instance status on the destination system
    1. One or more of the installed SAP instances are belonging to another SAP system and running with an instance number equal to one of the desired SAP instances -> FAIL
    2. All of the installed SAP instances are belonging to the same SAP system and running with the same instance numbers. In this case, we also run `sapcontrol -nr <number> -function GetSystemInstanceList` as the `<sidadm>` user for one of the desired SAP instances and get the SAP instance types from the last column. If the installed SAP instance types and numbers are matching the desired ones -> Role will report that the desired SAP instance(s) is/are already installed
    3. No SAP instance is installed, or all installed SAP instances are running with an instance number different from the desired one(s) -> Role will install the desired SAP instance(s)

3. SAP instance detection method:
- File `/usr/sap/hostctrl/exe/saphostctrl` exists? Run `/usr/sap/hostctrl/exe/saphostctrl -function ListInstances` and take its output for determining the installed SAP systems.
  - If `/usr/sap/hostctrl/exe/saphostctrl -function ListInstances` contains the desired instance numbers, we can assume that these instances are installed, so we can immediately fail if these belong to another SAP system (case 2.i.). If they belong to the  same SAP system ID (case 2.ii.), we need to run `sapcontrol` as described above, for determining the SAP instance type and can then decide if the desired instance(s) is/are installed or not. 
  - If `/usr/sap/hostctrl/exe/saphostctrl -function ListInstances` does not contain the desired instance numbers, there might also be a communication error and one or more of the desired instances might still be running or installed. In this case, we perform further checking on the OS level:
    - /usr/sap/`<SID>` exists -> set marker 1
    - /sapmnt/`<SID>` exists -> set marker 2
    - `<sidadm>` user exists -> set marker 3
    - If the sum of these three markers is 1 or 2 -> FAIL (something is broken)
    - /sapmnt/`<SID>`/profile/`<SID>*<number>`_`<hostname>` exists for all desired SAP instances -> set marker 4
    - If the sum of all four markers is 4 -> Role will report that the desired SAP instance(s) is/are already installed
    - If the sum of all four markers is 0 or if the sum of the first three markers is 3 and the fourth marker is 0 -> Role will install the desired SAP instance(s)

Thoughts?

**Comment by marcelmamula** [comment]
As we discussed together in PR and chat, we have wide range of combinations increasing complexity, but it can be alleviated by using combination matrix of different validations mentioned above.

Idempotency is not always behaving same, so we have to distinguish: Detection and skip, versus proceeding with installation.
**NOTE: Detection and skip does not inherently mean it is in idempotent state, because target system/instance could be of different configuration. **

PASS (proceed with sapinst):
- No SAP present with SID + Instance NR combination
- TODO: We need to double check `sidadm` as I had in past some failures where sapinst detected it already present and failed.

SKIP
- SAP present with SID + Instance NR combination
- **Do we want to check if it is of desired product and configuration?**

FAIL:
- SAP present with different SID but same Instance NR
- Unclean host
   - hostctrl exists but no instance detected (hostctrl, profile, sapservices check), `/usr/sap/SID` and `/sapmnt/SID` are present and contain files
   - hostctrl does not exist, `sidadm` is present

**Comment by berndfinger** [comment]
I tried some more commands which might be useful for detecting running or installed instances:

- Display SAP SIDs along with instance numbers and instance types: List all instances using `saphostctrl -function ListInstances`, save the SAP SID, then run `sapcontrol -nr <number> -function GetSystemInstanceList` on all the instances and display the SAP SID along with this information:
```
/usr/sap/hostctrl/exe/saphostctrl -function ListInstances | \
awk '/Inst Info :/{printf("SAP SID: %s\n", $4);
  system("/usr/sap/hostctrl/exe/sapcontrol -nr "$6" -function GetSystemInstanceList")}' | \
awk '/SAP SID:/{sap_sid=$NF}NF==7&&!/hostname/{printf("%s, %s\n", sap_sid, $0)}' | \
sort | uniq | sort -k6n
```
Sample output:
```
H83, host01, 42, 54213, 54214, 0.3, HDB|HDB_WORKER, GREEN
A01, host01, 0, 50013, 50014, 1, MESSAGESERVER|ENQUE, GREEN
A01, host01, 1, 50113, 50114, 3, ABAP|GATEWAY|ICMAN|IGS, GREEN
```

- Display all ports used by all SAP instances on a host: List all instances using `saphostctrl -function ListInstances`, save the SAP SID and the instance number, then run `sapcontrol -nr <number> -function GetAccessPointList` on all the instances and display the SAP SID and instance number along with this information:
```
/usr/sap/hostctrl/exe/saphostctrl -function ListInstances | \
awk '/Inst Info :/{sap_sid=$4; sap_number=$6;
  printf("SAP INSTANCE: %s %s\n", sap_sid, sap_number);
  system("/usr/sap/hostctrl/exe/sapcontrol -nr "$6" -function GetAccessPointList")}' | \
awk '/SAP INSTANCE:/{sap_sid=$3; sap_number=$4}
  NF==5&&!/address/&&!/127.0.0.1/{printf("%s, %s, %s\n", sap_sid, sap_number, $0)}'
```
Sample output:
```
H83, 42, 192.168.0.199, 54213, HTTP, sapstartsrv, Yes
H83, 42, 192.168.0.199, 54214, HTTPS, sapstartsrv, Yes
A01, 00, 192.168.0.199, 3200, ENQUEUES, enq_server, Yes
A01, 00, 192.168.0.199, 50013, HTTP, sapstartsrv, Yes
A01, 00, 192.168.0.199, 50014, HTTPS, sapstartsrv, Yes
A01, 00, 192.168.0.199, 3900, MS, msg_server, Yes
A01, 00, 192.168.0.199, 3600, MS, msg_server, Yes
A01, 00, 192.168.0.199, 8100, HTTP, msg_server, Yes
A01, 01, 192.168.0.199, 0, HTTP, icm, Yes
A01, 01, 192.168.0.199, 0, SMTP, icm, Yes
A01, 01, 192.168.0.199, 0, HTTPS, icm, Yes
A01, 01, 192.168.0.199, 50113, HTTP, sapstartsrv, Yes
A01, 01, 192.168.0.199, 50114, HTTPS, sapstartsrv, Yes
A01, 01, 192.168.0.199, 3301, RFC, gwrd, Yes
A01, 01, 192.168.0.199, 3201, DPTM, disp+work, Yes
A01, 01, 192.168.0.199, 40100, IGS, igsmux, Yes
A01, 01, 192.168.0.199, 40180, HTTP, igsmux, Yes
A01, 01, 192.168.0.199, 40101, IGS, igspw, Yes
A01, 01, 192.168.0.199, 40102, IGS, igspw, Yes
```

**Reply by sean-freeman** [reply]
I agree with the overall approach. I'd personally consider the approach required as less "idempotency of SWPM" and more "prevent overwrite of previous SWPM execution".  It's OK to error, in my opinion.

I would try to keep this more 'UNIXy' though. Less reliance on binary stdout, more reliance on files / state. For example:

Then, we could have this in different strictness levels:
```yaml
# When SAP SWPM is run multiple times on the same host, other SAP software instantiations may exist and conflict
# In some cases SAP SWPM will not gracefully fail and may cause errors
# The SWPM rerun check provides pseudo-idempotency, by checking for existing directories, files and listening ports
sap_swpm_rerun_check: "strict" # strict, ports_only, profiles_only
```

List of checks:

- check if OS Users exist
  - `{{ sap_swpm_sid | lower }}adm`

- check if dirs/subdirs exist
  - `/usr/sap/{{ sap_system_sid }}`
  - `/sapmnt/{{ sap_system_sid }}`
    - `/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_*{{ sap_swpm_ascs_instance_nr }}_{{ sap_swpm_ascs_instance_hostname }}`
    - `/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_*{{ sap_swpm_ers_instance_nr }}_{{ sap_swpm_ers_instance_hostname }}`
    - `/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_*{{ sap_swpm_pas_instance_nr }}_{{ sap_swpm_pas_instance_hostname }}`
    - `/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_*{{ sap_swpm_aas_instance_nr }}_{{ sap_swpm_aas_instance_hostname }}`

- check if port is already listening (e.g. `lsof` stdout to a register), and if listening port is an known SAP binary process (e.g. next Task, fail module loop over prior register)

- check if listed in /usr/sap/sapservices file

**Reply by sean-freeman** [reply]
### Critical listening ports to check

| **Product Name** | **Process Name** | **Service in etc/services** | **Port Default** | **Port Rule**` |
|---|---|---|---|---|
| Linux Pacemaker | pcsd | - | 2224 | - |
| Linux Pacemaker | pacemaker | - | 3121 | - |
| Linux Pacemaker | corosync | - | 5404 | - |
| Linux Pacemaker | corosync | - | 5405 | - |
| Linux Pacemaker | corosync | - | 5406 | - |
| Linux Pacemaker | corosync | - | 5407 | - |
| Linux Pacemaker | corosync | - | 5408 | - |
| Linux Pacemaker | corosync | - | 5409 | - |
| Linux Pacemaker | corosync | - | 5410 | - |
| Linux Pacemaker | corosync | - | 5411 | - |
| Linux Pacemaker | corosync | - | 5412 | - |
| SAP HANA | HTTPS | None | 4300 | `43<NN>` |
| SAP HANA | HTTP | None | 8000 | `80<NN>` |
| SAP HANA | indexserver | None | 30013 | `3<NN>13` |
| SAP HANA | indexserver | None | 30015 | `3<NN>15` |
| SAP HANA | SOAP/HTTP | None | 50013 | `5<NN>13` |
| SAP HANA | SOAP/HTTPS | None | 50014 | `5<NN>14` |
| SAP HANA - System Replication | nameserver | None | 40001 | `4<NN>01` |
| SAP HANA - System Replication | nameserver | None | 40002 | `4<NN>02` |
| SAP HANA - System Replication | nameserver | None | 40006 | `4<NN>06` |
| SAP HANA - System Replication | xsengine | None | None | `4<NN>40 – 4<NN>97` |
| SAP Host Agent | SAP Host Agent with SOAP/HTTP | saphostctrl | 1128 | `1128` |
| SAP Host Agent | SAP Host Agent with SOAP/HTTPS | saphostctrls | 1129 | `1129` |
| SAP NWAS | SAP Start Service HTTP | `sapctrl<NN>` | 50013 | `5<NN>13` |
| SAP NWAS | SAP Start Service HTTPS | `sapctrls<NN>` | 50014 | `5<NN>14` |
| SAP NWAS ABAP | SAP Dispatcher | `sapdp<NN>` | 3200 | `32<NN>` |
| SAP NWAS ABAP | Gateway | `sapgw<NN>` | 3300 | `33<NN>` |
| SAP NWAS ABAP | Message server | `sapms<SID>` | 3600 | `36<NN>` |
| SAP NWAS ABAP | Enqueue server | `sapdp<NN>` | 3900 | `39<NN>` |
| SAP NWAS ABAP | Gateway secured | `sapgw<NN>s` | 4800 | `48<NN>` |
| SAP NWAS ABAP | ICM HTTP | None | 8000 | `80<NN>` |
| SAP NWAS ABAP | Message server HTTP | None | 8100 | `81<NN>` |
| SAP NWAS ABAP | ICM HTTPS | None | 44300 | `443<NN>` |
| SAP NWAS ABAP | Message server HTTPS | None | 44400 | `444<NN>` |
| SAP NWAS ABAP | HTTP | `sapctrl<NN>` | 50013 | `5<NN>13` |
| SAP NWAS ABAP | HTTPS | `sapctrls<NN>` | 50014 | `5<NN>14` |
| SAP NWAS JAVA | P4 | None | 50004 | `5<NN>04` |
| SAP NWAS JAVA | P4 over HTTP tunneling | None | 50005 | `5<NN>05` |
| SAP NWAS JAVA | P4 over SSL | None | 50006 | `5<NN>06` |
| SAP NWAS JAVA | HTTP | `sapctrl<NN>` | 50013 | `5<NN>13` |
| SAP NWAS JAVA | HTTPS | `sapctrls<NN>` | 50014 | `5<NN>14` |
| SAP NWAS JAVA Central Services (SCS) | Gateway | `sapgw<NN>` | 3301 | `33<NN>` |
| SAP NWAS JAVA Central Services (SCS) | Gateway secured | `sapgw<NN>s` | 4800 | `48<NN>` |
| SAP NWAS JAVA Central Services (SCS) | HTTP | None | 8100 | `81<NN>` |
| SAP NWAS JAVA Central Services (SCS) | Message server port | `sapms<SID>` | 9310 | None |
| SAP NWAS JAVA Central Services (SCS) | HTTPS | None | 44400 | `444<NN>` |
| SAP NWAS JAVA Central Services (SCS) | HTTP | `sapctrl<NN>` | 50013 | `5<NN>13` |
| SAP NWAS JAVA Central Services (SCS) | HTTPS | `sapctrls<NN>` | 50014 | `5<NN>14` |
| SAP NWAS JAVA Central Services (SCS) | Enqueue server | None | 50116 | `5<NN>16` |

**Comment by rob0d** [comment]
Gents, you both are pretty much spot on. Detecting if an instance is installed in order to achieve idempotency is unrealistic without a huge effort. The best we can do is to "guess" with a  some level of certainty if what we are asking for is installed already or not. Then give the user choice of aborting or ignoring and hoping it will go well.

The key thing here is that we can't rely just on saphostctrl. SWPM checks presence of instance profile in /sapmnt/<SID>/profile and will happily damage .sapenv* files to do that and then fail saying instance is already installed.

What's worse, SWPM behaviour differs depending on which component is it installing and what are the versions e.g.
- for diag. agent and web disp it will happily overwrite the installation as long as the kernel release  (SAPEXE*.SAR) is the same. If the kernel release differs e.g. SAPEXE3xx is installed and we want to re-install SAPEXE4xx, it will fail.
- Similarly I'm 82.7% sure that dbload will drop the DB and load again.
- Onehost and ASCS/ERS will fail if profile exists.
- I'm not sure about PAS/AAS, but they will probably fail too.

In summary, we can't rely on SWPM to do the right thing, we should prevent it from running if we are not reasonably sure it's safe.

I wrote this last year, but didn't take beyond testing the principle. `found_nw` gets the higher the more likely it's a system is installed.
```yaml
- hosts: nwas_abap_pas, nwas_abap_aas
  become: true
 
  vars:
    found_nw: 0    
 
  tasks:
    - name: Ask saphostcontrol for a list of services
      shell: "/usr/sap/hostctrl/exe/saphostctrl -function ListInstances | grep '{{ sap_system_sid }} - {{ instance_nr }}' |awk '{print $4,$6,$8}'"
      #shell: "/usr/sap/hostctrl/exe/saphostctrl -function ListInstances | grep '{{ sap_system_sid }}' |awk '{print $4,$6,$8}'"
      register: saphostctrl
      ignore_errors: yes
      changed_when: false
     
    - name: Check if saphostcontrol hostname matches
      set_fact:
        saphostcontrolhostname: true            
      loop: "{{ saphostctrl.stdout_lines }}"
      when: item.split()[2]  ==  nbs_nwas_abap_pas_short
 
    - name: Evaluate saphostcontrol hostname
      set_fact:
        found_nw: "{{ found_nw | int + 1 }}"
      when:
       - saphostcontrolhostname is defined
       - saphostcontrolhostname == true
           
    - name: Check sapservices contain the SID and Instance
      shell: "grep -q 'SAP{{ sap_system_sid }}_{{ instance_nr }}' /usr/sap/sapservices"
      register: sapservices
      ignore_errors: yes
      changed_when: false
 
    - name: Evaluate if instance present in sapservices
      set_fact:
        found_nw: "{{ found_nw | int + 1 }}"
      when: sapservices.rc == 0
 
    - name: Check if the Instance profile exists
      find:
        paths: "/sapmnt/{{ sap_system_sid }}/profile/"
        patterns: "{{ sap_system_sid }}_*{{ instance_nr }}_{{ instance_host }}"
      register: sap_profiles
 
    - name: Evaluate sap profiles
      set_fact:
        found_nw: "{{ found_nw | int + 1 }}"
      when: sap_profiles.matched > 0
 
    - name: Finished
      debug:
        var: found_nw
 ```
