### DISCUSSION TITLE
A simple template to deploy a solman diag agent.

### DISCUSSION THREAD

**Discussion by wuftymerguftyguff** [sap-linuxlab/community.sap_install#493] [Ideas]
Deploying a diagnostic agent is probably my most repeated swpm task.

It would be great if sap_install had a simple way of automating this and optionally configuring a deployed agent.

Thoughts?

**Comment by sean-freeman** [comment]
@wuftymerguftyguff It's not something I have actively attempted via `sap_swpm` Ansible Role, but it should be possible.

At a guess, try the below snippet - I only spent 10mins on it but it should be pretty close. If you can prove it, then I could append to the _"do-it-for-me, thanks"_ Inifile Generate method. Drop me an [email](https://github.com/sap-linuxlab/community.sap_install/blob/main/galaxy.yml#L21) if you want to work on it together.

I grabbed the sample values from:
> https://help.sap.com/docs/SLTOOLSET/ea34afd8e8d34085ac6fbc581cd3b7f3/15e87752ea2a7b6ae10000000a423f68.html?version=CURRENT_VERSION#n1t


```yaml
- name: Ansible Play
  hosts: all
  become: true

  tasks:

    - name: Execute Ansible Module with system Python to download installation media for SAP Diagnostics Agent on Linux
      community.sap_launchpad.software_center_download:
        suser_id: "{{ sap_id_user }}"
        suser_password: "{{ sap_id_user_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "/software"
      loop:
        - 'SMDA720_SP14_11-80003641.SAR'
        - 'SWPM10SP38_5-20009701.SAR' # Linux x86_64
        - 'SAPJVM8_95-80000202.SAR' # Linux x86_64
        - 'SAPHOSTAGENT61_61-80004822.SAR' # SAP Host Agent 7.22 Linux x86_64
        - 'SAPEXE_1100-80002573.SAR' # Kernel Part I (753)
        - 'SAPEXEDB_1100-80002572.SAR' # Kernel Part II (753), SAP HANA
      loop_control:
        label: "{{ item }} : {{ download_task.msg }}"
      register: download_task

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_install_media_detect }
      vars:
        - sap_install_media_detect_swpm: true
        - sap_install_media_detect_hostagent: true
        - sap_install_media_detect_kernel: true

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: { role: community.sap_install.sap_swpm }
      vars:
        sap_swpm_ansible_role_mode: advanced_templates
        sap_swpm_templates_product_input: sap_diagnostics_agent_753
        sap_swpm_templates_install_dictionary:
          sap_diagnostics_agent_753:
            sap_swpm_product_catalog_id: NW_DiagnosticsAgent:GENERIC.IND.PD
            sap_swpm_inifile_custom_values_dictionary:
              hostAgent.sapAdmPassword: Klmnop123456
              DiagnosticsAgent.LogicalHostName: hostname1
              DiagnosticsAgent.SID: DAA
              DiagnosticsAgent.InstanceNumber: 98
              DiagnosticsAgent.dasidAdmPassword: Abcdef123456
              DiagnosticsAgent.SAPJVMVersion: SAPJVM8
              DiagnosticsAgent.SolMan.Connection: solman # solman or none
              DiagnosticsAgent.SolMan.UseSSL: true
              DiagnosticsAgent.SolMan.HostName: host.domain.corp
              DiagnosticsAgent.SolMan.PortNumber: 44401
              # DiagnosticsAgent.SolMan.UserName
              # DiagnosticsAgent.SolMan.Password
              # DiagnosticsAgent.SAProuter.RouteString
              # DiagnosticsAgent.SAProuter.Password
              # DiagnosticsAgent.SLD.Connection
              # DiagnosticsAgent.SLD.HostName
              # DiagnosticsAgent.SLD.Password
              # DiagnosticsAgent.SLD.PortNumber
              # DiagnosticsAgent.SLD.UseHTTPS
              # DiagnosticsAgent.SLD.UserName
              # DiagnosticsAgent.installSAPHostAgent
```

**Reply by wuftymerguftyguff** [reply]
Thanks, I will have  a play with this and let you know how I get on.

**Reply by sean-freeman** [reply]
@wuftymerguftyguff How did you get on?

**Reply by sean-freeman** [reply]
@wuftymerguftyguff Did this succeed? If so please confirm and close this discussion

**Reply by sean-freeman** [reply]
@wuftymerguftyguff Without confirmation, this discussion will be closed within 1 week

**Comment by rob0d** [comment]
Hi @sean-freeman,
I used what you suggested above as a starting point. There are quite a few variations how this can be configured. The code below is based on my needs, but can be adjusted by running SWPM SMD installation and then checking what's in inifile.params and putting it into the code.
This is based on the updated way of connecting SMD to SolMan which requires username/password  (status March 2024) and on SWPM1 SP40.
Also I couldn't get sap_install_media_detect to work as sap_install_media_detect_kernel: true checks for the existence of SAPEXEDB* which isn't used with Diag agent installation. So the following is a complete code based on assumption that everything is /install/diagagents folder.


```
    - name: Execute Ansible Role sap_swpm
      vars:
        sap_swpm_software_path: /install/diagagents
        sap_swpm_sapcar_path: /install/diagagents
        sap_swpm_sapcar_file_name: SAPCAR.EXE
        sap_swpm_swpm_path: /install/diagagents
        sap_swpm_ansible_role_mode: advanced_templates
        sap_swpm_generic: true
        sap_swpm_templates_product_input: sap_diagnostics_agent_754
        sap_swpm_templates_install_dictionary:
          sap_diagnostics_agent_754:
            sap_swpm_product_catalog_id: NW_DiagnosticsAgent:GENERIC.IND.PD
            sap_swpm_inifile_custom_values_dictionary:
              DiagnosticsAgent.InstanceNumber: "97"
              DiagnosticsAgent.LogicalHostName: "{{ inventory_hostname_short }}"
              DiagnosticsAgent.SID: "DAA"
              DiagnosticsAgent.SolMan.HostName: "<solman java scs fqdn"
              DiagnosticsAgent.SolMan.Password: "<secret>"
              DiagnosticsAgent.SolMan.PortNumber: "81<SCS Inst.No>"
              DiagnosticsAgent.SolMan.UseSSL: "false"
              DiagnosticsAgent.SolMan.UserName: "SMDA_INSTALL"
              DiagnosticsAgent.installSAPHostAgent: "false"
              NW_Unpack.sapExeSar: "/install/diagagents/SAPEXE_300-80007612.SAR"
              archives.downloadBasket: "/install/diagagents"
              nwUsers.sapsysGID: "500"

      ansible.builtin.include_role:
        name: { role: ../roles/sap_swpm }
```
