### DISCUSSION TITLE
HANA LSS won't install. What am I missing?

### DISCUSSION THREAD

**Discussion by audiolomb** [sap-linuxlab/community.sap_install#494] [Q&A]
When installing SAP HANA, I am getting this error:

"Running in batch mode", "  Installation of SAP HANA Local Secure Store is possible only in optimized execution mode"

I see that there are variables defined to set the LSS password in the sap_hana_install role, so I suppose LSS install should be possible.

What am I missing?

Thank you,
Claudio

**Comment by sean-freeman** [comment]
Hi @audiolomb,

Please note, I always use SSFS so the below is just an explanation and you would need to test this for yourself. After a successful test, I could add a few extra notes into the README for SSFS vs. LSS.

How this particular Ansible Role works, allows for customisation as hdblcm changes over time. This is achieved using the Ansible Task "Create the hdblcm configfile dynamically" under `/roles/sap_hana_install/tasks/pre_install/hdblcm_configfile.yml`, which looks for any Ansible Variable that is `sap_hana_install` prefix + `hdblcm parameter name` (see full [parameter reference list on the SAP HANA Server Installation and Update Guide](https://help.sap.com/docs/SAP_HANA_PLATFORM/2c1988d620e04368aa4103bf26f17727/c16432a77b6144dcb75aace2b4fcacff.html?locale=en-US))

Therefore, when executing with Ansible, you could access these hdblcm parameters by using Ansible Variables such as:
```yaml
sap_hana_install_install_execution_mode: optimized
sap_hana_install_secure_store: localsecurestore
sap_hana_install_lss_inst_path: /lss/shared
sap_hana_install_lss_user_password: Passw0rd1%
sap_hana_install_lss_userid: 5000
sap_hana_install_lss_groupid: 5001
sap_hana_install_lss_user_home: "/usr/sap/{{sap_hana_install_sid}}/lss/home"
sap_hana_install_lss_user_shell: /bin/sh
sap_hana_install_lss_backup_password: Passw0rd1%
```

Which would be equal to execution manually from hdblcm command line as `--parameter` operators or a hdblcm config file created such as:
```shell
[General]

# Install Execution Mode ( Default: standard; Valid values: standard | optimized )
install_execution_mode=standard

[Server]

# SAP HANA Database secure store ( Default: ssfs; Valid values: ssfs | localsecurestore )
secure_store=localsecurestore

[lss]

# Installation Path for Local Secure Store ( Default: /lss/shared )
lss_inst_path=/lss/shared

# Local Secure Store User Password
lss_user_password=

# Local Secure Store User ID
lss_userid=5000

# Local Secure Store User Group ID
lss_groupid=5001

# Local Secure Store User Home Directory
lss_user_home=/usr/sap/__HDB_SID__/lss/home

# Local Secure Store User Login Shell ( Default: /bin/sh )
lss_user_shell=/bin/sh

# Local Secure Store Auto Backup Password
lss_backup_password=
```
