### ISSUE TITLE
sap_swpm: Sanitize variables before running String check

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_install#1030]
### Bug Description

`sap_swpm` role is checking variables (e.g. `sap_swpm_product_catalog_id`) using `String` operations, without checking if it is actually `String`.

https://github.com/sap-linuxlab/community.sap_install/blob/8a89687bc58f865f6d77a38d960323345ff2a60f/roles/sap_swpm/tasks/pre_install/install_type.yml#L33

### Bug reproduction

Simple test is enough
```yaml
    - name: SAP SWPM Pre Install - Check if System Copy (Backup/Restore)
      ansible.builtin.set_fact:
        sap_swpm_swpm_installation_type: "restore"
        sap_swpm_swpm_installation_header: "System Copy restore from backup"
      when:
        - "'.CP' in sap_swpm_product_catalog_id"
      vars:
        sap_swpm_product_catalog_id: 111
```

### Solution
This can be fixed by adding sanitization:
```yaml
    - name: SAP SWPM Pre Install - Check if System Copy (Backup/Restore)
      ansible.builtin.set_fact:
        sap_swpm_swpm_installation_type: "restore"
        sap_swpm_swpm_installation_header: "System Copy restore from backup"
      when:
        - "'.CP' in sap_swpm_product_catalog_id | string"
 ```
