### ISSUE TITLE
sap_install_media_detect: backup functionality missing

### ISSUE THREAD

**Issue by sean-freeman** [sap-linuxlab/community.sap_install#1055]
### Ansible Role

sap_install_media_detect

### OS Family

N/A

### Ansible Controller - Python version

Python 3.13.3

### Ansible-core version

ansible [core 2.16.13]

### Bug Description

sap_install_media_detect v1.2.3 had minor backup functionality, using 2 vars `sap_install_media_detect_backup` and `sap_install_media_detect_backup_directory` ....

```yaml
- name: SAP Install Media Detect - Complete Data Backup files for SAP HANA
  include_tasks: "detect_backup_saphana.yml"
  when:
    - sap_install_media_detect_backup == "saphana"
```

```yaml
- name: Identify SAP HANA Backup files
  ansible.builtin.find:
    paths: "{{ sap_install_media_detect_backup_directory }}"
    recurse: yes
    file_type: directory
    patterns: '.*COMPLETE.*'
    use_regex: yes
  register: backup_saphana_find_dir
```

---

This was removed in the v1.3.x overhaul.

There is no usage of the vars listed in the defaults, they can be removed:
```yaml
# e.g. /db_backup
sap_install_media_detect_backup_directory:

# saphana
sap_install_media_detect_backup:
```

And the file check exists, but there are no further actions taken for files detected as type `saphana_backup`:
`sapfile`
```shell
/COMPLETE/{_sap_file_type="saphana_backup"; exit}
```

Action taken should be, set the vars such as:
```yaml
sap_swpm_backup_location: "/software/backup"
sap_swpm_backup_prefix: "COMPLETE_DATA_BACKUP"
```

### Bug reproduction

Run System Copy restore from SAP HANA complete data backup

### Community participation

Unfortunately I am not in a position to help with the bug fix
