### ISSUE TITLE
Add new role for managing /etc/hosts entries

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#171]
We need correct updates in /etc/hosts several times. So it is valuable to make a separate role out of it.

Example
```
- name: ensure /etc/hosts is updated 
  include_role: sap_update_etc_host
  var:
        sap_update_etc_hosts_name: item.name
        sap_update_etc_hosts_domain: item.domain
        sap_update_etc_host_ip: item.ip
        sap_update_etc_hosts_add_alias: ""
        sap_update_etc_hosts_keep_old_alias: default(true )
        sap_update_etc_hosts_check_dns: default(true)
        sap_update_etc_hosts_dns_error_fatal: false
        sap_update_etc_hosts_name_length: 13 
  loop:
    - { ip: 1.2.3.4, name: node1 , domain: example.com }
    - name: node2
      domain: example.com
      ip: 1.2.3.4
```

Tasks: will be extracted from sap_general_preconfigure
