### ISSUE TITLE
sap*preconfigure: SLES kernel parameters are not set by saptune

### ISSUE THREAD

**Issue by herrmie** [sap-linuxlab/community.sap_install#337]
## Problem

SLES kernel parameters (like numa_balancing, transparent_hugepage, intel_idle.max_cstate, processor.max_cstate) are not set by saptune

on SLES4SAP SAP Note https://launchpad.support.sap.com/#/notes/2684254 says to set the kernel parameter:
```
numa_balancing=disable
transparent_hugepage=never
intel_idle.max_cstate=1
processor.max_cstate=1
```

saptune is not setting them in the grub.cfg

## Solution
Add tasks to add them to grub.cfg
E.g
```
    - name: Set GRUB entries # noqa yaml[line-length]
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="splash=silent mitigations=auto quiet numa_balancing=disable transparent_hugepage=never intel_idle.max_cstate=1 processor.max_cstate=1 audit=1"'
      register: set_grub_entries

    - name: GRUB mkconfig # noqa command-instead-of-shell no-handler
      ansible.builtin.shell:
        cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: 
        - set_grub_entries.changed

    - name: GRUB.cfg permissions
      ansible.builtin.file:
        path: /boot/grub2/grub.cfg
        mode: "0600"
```
