### ISSUE TITLE
sap_general_preconfigure: RHEL 8 system deletes network interface during installation step when created with image provisioning

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#34]
the default image in GCP has not installed the package NetworkManager-config-server.

This adds a NetworkManager configuration file to make it behave more like the old "network" service. In particular, it stops NetworkManager from automatically running DHCP on unconfigured ethernet devices, and allows connections with static IP addresses to be brought up even on ethernet devices with no carrier. This package is intended to be installed by default for server
deployments.

Hence the role installs it automatically, with the consequence that dhcp is no longer started on the network interfaces in GCP after reboot and the machine is disconnected from the network.

One easy option is to print a warning if that happens, the other option is to "define" the existing network config if it is unconfigured

**Comment by rhmk** [comment]
Everything works as designed. The follwowing task before a reboot is fixing the issue:
```
    - name: ensure network configuration is persistent
      include_role:
         name: rhel-system-roles.network
      vars:
         network_provider: nm
         network_connections:
           - name: "{{ ansible_default_ipv4.alias }}"
             mac: "{{ ansible_default_ipv4.macaddress }}"
             interface_name: "{{ ansible_default_ipv4.interface }}"
             type: ethernet
             ip:
                     dhcp4: true
                     dhcp4_send_hostname: true 

```
It will create a file in /etc/sysconfig/network-scripts to make the connection persistent.
 For production with multiple interfaces, it would be a good practice to run the network role anyway after VM creation

So a possible probe for a warning in the playbook network section could be  no /etc/sysconfig/network-scripts/ifcfg-* files
 or  run a " nmcli c s " command and check if the file ifcfg-$1 do exist.
