### ISSUE TITLE
sap_ha_pacemaker_cluster - SAPHanaTopology shows as promotable resource

### ISSUE THREAD

**Issue by waorb** [sap-linuxlab/community.sap_install#365]
Next issue observed during the current tests.
The defined SAPHanaTopology resource has the promotable attribute set.

````

Node List:
  * Online: [ cl-h01-1 (1) cl-h01-2 (2) ]

Full List of Resources:
  * res_fence_ibm_powervs	(stonith:fence_ibm_powervs):	 Started cl-h01-1
  * vip_H01_00_primary	(ocf::heartbeat:IPaddr2):	 Started cl-h01-1
  * Clone Set: SAPHanaTopology_H01_00-clone [SAPHanaTopology_H01_00] (promotable):
    * SAPHanaTopology_H01_00	(ocf::heartbeat:SAPHanaTopology):	 Slave cl-h01-1
    * SAPHanaTopology_H01_00	(ocf::heartbeat:SAPHanaTopology):	 Slave cl-h01-2
  * Clone Set: SAPHana_H01_00-clone [SAPHana_H01_00] (promotable):
    * SAPHana_H01_00	(ocf::heartbeat:SAPHana):	 Master cl-h01-1
    * SAPHana_H01_00	(ocf::heartbeat:SAPHana):	 Starting cl-h01-2
````
Here is the resource definition as it is created by the cluster role:
````
# pcs resource config SAPHanaTopology_H01_00-clone
 Clone: SAPHanaTopology_H01_00-clone
  Meta Attrs: clone-max=2 clone-node-max=1 promotable=true
  Resource: SAPHanaTopology_H01_00 (class=ocf provider=heartbeat type=SAPHanaTopology)
   Attributes: InstanceNumber=00 SID=H01
   Operations: methods interval=0s timeout=5 (SAPHanaTopology_H01_00-methods-interval-0s)
               monitor interval=10 timeout=600 (SAPHanaTopology_H01_00-monitor-interval-10)
               reload interval=0s timeout=5 (SAPHanaTopology_H01_00-reload-interval-0s)
               start interval=0s timeout=600 (SAPHanaTopology_H01_00-start-interval-0s)
               stop interval=0s timeout=600 (SAPHanaTopology_H01_00-stop-interval-0s)
````

The code in construct_vars_hana_common.yml actually defines a _**promotable: "no"**_ parameter.
I don't know where this is lost.

````
- name: "SAP HA Prepare Pacemaker - Add resource clone: SAP HANA Topology"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_resource_clones: "{{ __sap_ha_pacemaker_cluster_resource_clones + [__clone_topology] }}"
  vars:
    __clone_topology:
      resource_id: "{{ sap_ha_pacemaker_cluster_hana_topology_resource_name }}"
      promotable: "no"
      meta_attrs:
        - attrs:
            - name: clone-max
              value: 2
            - name: clone-node-max
              value: 1
        - name: interleave
          value: "true"
  when:
    - __clone_topology.resource_id not in (__sap_ha_pacemaker_cluster_resource_clones | map(attribute='resource_id'))
````
