### ISSUE TITLE
sap_general_preconfigure: dict elements of parameters (if present) should also have type and description

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#516]
Suggested addition to `sap_general_preconfigure_kernel_parameters` in `meta/argument_specs.yml` (and related entries to `README.md` and `defaults/main.yml`):
```
        options:
          name:
            type: str
            description:
              - Name of the kernel parameter
          value:
            type: str
            description:
              - Value of the kernel parameter
```
