### ISSUE TITLE
collection: Cleanup for ansible-lint 6.22.0

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#535]
We should prepare for a version bump of ansible-lint.

**Comment by berndfinger** [comment]
I tried to solve:
```
risky-shell-pipe: Shells that use pipes should set the pipefail option.
tasks/RedHat/installation.yml:167 Task/Handler: Create a list of minimum required package versions to be installed
```
by using the package module instead of the shell command sequence for ensuring a minimum package version.
However, when testing the following code on a RHEL 8.8 system with `kernel` `4.18.0-477.10.1.el8_8`, only the package `kernel-core` gets installed to `4.18.0-477.27.1.el8_8` (and the system will boot into `kernel-4.18.0-477.27.1.el8_8`) but neither the package `kernel-modules` nor the package `kernel` will be installed. So we can unfortunately not replace the complex `awk` command sequence of the task mentioned above by the much simpler code:
```
- name: Define a new variable containing package name and version
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_register_minpkglist: "{{ __sap_hana_preconfigure_register_minpkglist | d([]) + [ line_item[0] + ' >= ' + line_item[1] ] }}"
  loop: "{{ __sap_hana_preconfigure_min_pkgs }}"
  loop_control:
    loop_var: line_item

- name: Install minimum packages if required
  ansible.builtin.package:
    name: "{{ __sap_hana_preconfigure_register_minpkglist }}"
    state: present
```
