### ISSUE TITLE
sap_swpm: Reduce sapinst log output to provide important information

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_install#568]
Current failed check will dump huge amount of information directly from sapinst log files. This is amount that is not required for investigation of failure and we need to filter it out a bit. My test runs produced so many lines of output that it cleared my whole console, rendering actual ansible log useless, being replaced by part of sapinst log.

@sean-freeman @berndfinger Updated as I am currently testing sap_infrastructure and my SWPM is failing so I can test this.

Proposal to limit output to last 50 or so lines
```
- name: SAP SWPM - Verify if sapinst process finished successfully
  ansible.builtin.async_status:
    jid: "{{ __sap_swpm_register_sapinst_async_job.ansible_job_id }}"
  register: __sap_swpm_register_sapinst
  ignore_errors: true
  no_log: true

- name: SAP SWPM - Detect failure and show limited output
  ansible.builtin.fail:
    msg: "{{ __sap_swpm_register_sapinst.stdout_lines[-50:] }}"
  when: __sap_swpm_register_sapinst.finished != 1 or __sap_swpm_register_sapinst.rc != 0
```
- failed_when is removed to make sure async does not fail
- no_log is introduced to remove hundreds and thousands of lines from sapinst_dev output
- Fail task is added to show limited output.

Variation to show only ERROR, but it will cut off important part because Errors are multi line.
```
- name: SAP SWPM - Detect failure and show limited output
  ansible.builtin.fail:
    msg: "{{ __sap_swpm_register_sapinst.stdout_lines | select('match', 'ERROR.*') | list }}"
  when: __sap_swpm_register_sapinst.finished != 1 or __sap_swpm_register_sapinst.rc != 0
```

Affected line: https://github.com/sap-linuxlab/community.sap_install/blob/d047f9343f1bd2ac970e02b33964281a094f996d/roles/sap_swpm/tasks/swpm.yml#L84

**Comment by berndfinger** [comment]
@marcelmamula Are you OK with 200 lines of output? I will then implement and test it.

**Comment by kksat** [comment]
@berndfinger @marcelmamula @sean-freeman another option would be to suppress non error messages. See example 

https://github.com/redhat-sap/rh_operations/blob/4f2584de0651b58e4f99003e6bc0108ca4b71888/roles/sapinst/tasks/main.yml#L61

how to use parameter SAPINST_MESSAGE_CONSOLE_THRESHOLD

And here is default parameter value
https://github.com/redhat-sap/rh_operations/blob/4f2584de0651b58e4f99003e6bc0108ca4b71888/roles/sapinst/defaults/main.yml#L26

One can get list of supported parameters for sapinst with 

```bash
./sapinst -p
```

Also for your information https://help.sap.com/docs/SUPPORT_CONTENT/sl/3362916813.html

**Comment by marcelmamula** [comment]
@berndfinger 200 seems bit too much for console to be readable. Error root cause is always 1-3 search results for ERR/ERROR in sapinst log file from bottom, which can be hundreds of lines, but if we purposefully filter out `err/ERR/error/ERROR` then we should be able to see it more clearly.

@kksat Are you sure it works?
Default value is already "error" and it shows everything, not just errors.

From last link you provided:
```
•SAPINST_MESSAGE_CONSOLE_THRESHOLD:

trace level console  values: flow_trace, trace, info, phase, warning, error, external(for ACC);  default: error
```

**Comment by kksat** [comment]
@marcelmamula 
I am certain that it works on RHEL ;). Maybe one has to add this parameter for it to work or default is not as it is documented, SAP is strange sometimes.

Colleagues from RH can access these links 
https://ara.saponrhel.org/results/19823.html - parameter set to 'error'
https://ara.saponrhel.org/results/1618.html - parameter not set
and see for themselves. 

Others will have to trust my word.

**Comment by marcelmamula** [comment]
@kksat My comment was more about what would this change do since default is already `error`, then enforcing same value as default, would not change a thing.

This issue is raised for something else. We are not talking about SWPM actual output, but followup task https://github.com/sap-linuxlab/community.sap_install/blob/c7da3982572e6e1167c0b14b6c9f33b3516df52c/roles/sap_swpm/tasks/swpm.yml#L69C3-L69C67 which dumps everything into console.

That is why I proposed to remove `failed_when` and replace it with debug task to show curated output.
```yaml
- name: SAP SWPM - Verify if sapinst process finished successfully
  ansible.builtin.async_status:
    jid: "{{ __sap_swpm_register_sapinst_async_job.ansible_job_id }}"
  register: __sap_swpm_register_sapinst
  ignore_errors: true
  no_log: true

- name: SAP SWPM - Detect failure and show limited output
  ansible.builtin.fail:
    msg: "{{ __sap_swpm_register_sapinst.stdout_lines[-50:] }}"
  when: __sap_swpm_register_sapinst.finished != 1 or __sap_swpm_register_sapinst.rc != 0
```
