### ISSUE TITLE
sap_anydb_install_oracle: Handle rc > 0 in Install Oracle DB task

### ISSUE THREAD

**Issue by rnozaki** [sap-linuxlab/community.sap_install#584]
In the task [community.sap_install.sap_anydb_install_oracle : Oracle DB - Install Oracle DB], the task accepts when the scripts returns code is in [ 0,1 ]. 

So the task finishes successfully even for rc=1. In one of my tests, the script was not found, finished with rc=1, and the task was considered "Successful" and the playbook proceeded to the next task, which does not make sense.

Any reason (maybe historical) for accepting rc=1 here?

My suggestion is to only accept rc=0 for success.

```
- name: Oracle DB - Install Oracle DB
  become: true
  become_user: oracle
  args:
    executable: /bin/csh
    chdir: "{{ sap_anydb_install_oracle_base }}/dvd/19.0.0/"
  register: __sap_anydb_install_oracle_install_exec
  changed_when: "'SAP RUNINSTALLER: Completed' in __sap_anydb_install_oracle_install_exec.stdout"
  failed_when: "__sap_anydb_install_oracle_install_exec.rc not in [ 0, 1 ]"
  ...
```
