### ISSUE TITLE
sap_ha_pacemaker_cluster: sap_ha_pacemaker_cluster_hacluster_user_password ignored

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_install#615]
Current workflow is not accepting variable sap_ha_pacemaker_cluster_hacluster_user_password for HA cluster password because:
1. ha_cluster_hacluster_password is always defined in defaults as ""
2. __sap_ha_pacemaker_cluster_hacluster_user_password i always emptied because ha_cluster_hacluster_password  is always defined.
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/import_hacluster_vars_from_inventory.yml#L68
3. Construct common vars is always skipped because __sap_ha_pacemaker_cluster_hacluster_user_password  is defined in previous step, so sap_ha_pacemaker_cluster_hacluster_user_password  is never used.
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/construct_vars_common.yml#L21
4. ha_cluster_hacluster_password is "" because __sap_ha_pacemaker_cluster_hacluster_user_password is defined and empty ""
https://github.com/sap-linuxlab/community.sap_install/blob/5ee5cbe030ad152edfe96567155812f9abcdc25f/roles/sap_ha_pacemaker_cluster/tasks/construct_final_hacluster_vars.yml#L74

Solution: Update import_hacluster_vars file with conditional for empty string for ha_cluster_hacluster_password  from defaults.
```
# ha_cluster_hacluster_password
- name: "SAP HA Prepare Pacemaker - (ha_cluster) Register parameter 'ha_cluster_repos'"
  when:
    - ha_cluster_hacluster_password is defined
    - ha_cluster_hacluster_password | length > 0
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_hacluster_user_password: "{{ ha_cluster_hacluster_password }}"
  no_log: true  # handle credentials with care
```
