### ISSUE TITLE
sap_storage_setup: not working after 1.2.3

### ISSUE THREAD

**Issue by herrmie** [sap-linuxlab/community.sap_install#623]
Hello,
I have used the sap_storage_setup role for a long time with version 1.2.3, without any issues. 
Now, I have use the newest version and I am wondering why I can't define the devices like in the 1.2.3 version. 
I have understand from the code, that the role will use undefined disks. But what is the clarification if I use a disk, is it the disk_size? If yes, this is not good. Because, if I have a disk with 100GB and want to have 20 GB reserved in the VG, that will not be possible I guess.
Please check the role and let me know how I get it working.

```yaml
sap_storage_setup_definition:
- disk_size: "{{ vm_hana_usr_sap }}G"
  filesystem_type: xfs
  name: "usrsap"
  mountpoint: "/usr/sap/{{ SID }}"
  lvm_vg_name: "vg_usr_sap"
  lvm_lv_name: "lv_usr_sap"
- disk_size: "{{ vm_hana_backup }}G"
  filesystem_type: xfs
  name: "backup"
  mountpoint: "/backup"
  lvm_vg_name: "vg_backup"
  lvm_lv_name: "lv_backup"
- disk_size: "{{ vm_hana_shared }}G"
  filesystem_type: xfs
  name: "hanashared"
  mountpoint: "/hana/shared"
  lvm_vg_name: "vg_hana_shared"
  lvm_lv_name: "lv_hana_shared"
- disk_size: "{{ vm_hana_data }}G"
  filesystem_type: xfs
  name: "hanadata"
  mountpoint: "/hana/data"
  lvm_vg_name: "vg_hana_data"
  lvm_lv_name: "lv_hana_data"
- disk_size: "{{ vm_hana_log }}G"
  filesystem_type: xfs
  name: "hanalog"
  mountpoint: "/hana/log"
  lvm_vg_name: "vg_hana_log"
  lvm_lv_name: "lv_hana_log"
```

Thanks in advance and best regards,
Steffen Herrmann

**Comment by sean-freeman** [comment]
@herrmie `TL;DR - you'll need to re-code`

In [v1.3.0](https://github.com/sap-linuxlab/community.sap_install/releases/tag/1.3.0) feature added `sap_storage_setup: Overhaul/Rewrite with breaking changes`. Prior to this, the Ansible Role was extremely incomplete ([for example accidental first day of coding dev notes left in the codebase](https://github.com/sap-linuxlab/community.sap_install/blob/60f5f40497d54c46b0bd3f79ef1fef4ada148119/roles/sap_storage_setup/tasks/aws_main.yml#L6))

The storage setup Ansible Role is now able to parse and setup block storage or file storage (NFS) e.g. SAP NWAS (ABAP/JAVA) for High Availability

The LVM LV is set by default to [100%](https://github.com/sap-linuxlab/community.sap_install/blob/1.3.4/roles/sap_storage_setup/tasks/generic_tasks/configure_local_filesystems.yml#L20), and the other LVM operators are optional in the definition, for example:
```yaml
sap_storage_setup_definition:
  - name: hana_data
    mountpoint: /hana/data
    disk_size: 384                 # size in GB, integer
    filesystem_type: xfs           # default: xfs
    #lvm_lv_name:                  # default: lv_<element_name>
    #lvm_lv_stripes: 2             # default: null, number of disks to stripe over
    #lvm_lv_stripe_size: 128K      # default: 64K, defined by the OS. Akin to Virtualized Block Size
    #lvm_vg_name:                  # default: vg_<element name>
    #lvm_vg_options:               # default: none, additional LVM VG options as string in LVM options syntax (e.g. "--dataalignment XX ..." to override MiB offset from disk start before first LVM VG Physical Extent)
    #lvm_vg_physical_extent_size:  # default: 4, uses 4 MiB default and difficult to change once set. Akin to Physical Block Size
    #lvm_pv_device:                # default: discovered ansible_devices matching the target size
    #lvm_pv_options:               # default: none, additional LVM PV options as string in LVM options syntax (e.g. "--dataalignment XX ..." to override MiB offset from disk start before first LVM PV Physical Extent)
    #nfs_path:                     # subdirectory path on the NFS server
    #nfs_server:                   # NFS server and parent directory (e.g. nfs.com:/share1). default: {{ sap_storage_setup_nfs_server }}
    #nfs_filesystem_type:          # default: {{ sap_storage_setup_nfs_filesystem_type }}
    #nfs_mount_options:            # default: {{ sap_storage_setup_nfs_mount_options }}
    #swap_path:
```

**Comment by rainerleber** [comment]
I think @herrmie want to define the disks which are used for each mount point manually as an option. Like:

```
sap_storage_setup_definition:
  - name: hana_data
    mountpoint: /hana/data
    disk_size: 384
    filesystem_type: xfs
    ***disk: /dev/sdb***
    
 ```
