### ISSUE TITLE
sap_*_preconfigure: package_facts

### ISSUE THREAD

**Issue by sean-freeman** [sap-linuxlab/community.sap_install#649]
sap_*_preconfigure Ansible Role's may fail upon first usage of Ansible Module `package_facts` when python3-rpm OS Package is not installed for the System Python.

Specifically noted [for SLES in the Ansible Module in-line documentation](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/package_facts.py#L39) but should be considered for RHEL also as an administrator may alter any OS Image.

```yaml
- name: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python - RHEL
  ansible.builtin.command: yum install --assumeyes python3-rpm
  when: ansible_os_family == "RedHat"

- name: Ensure OS Package for Python Lib of rpm bindings is enabled for System Python - SLES
  ansible.builtin.command: zypper install --no-confirm --auto-agree-with-licenses python3-rpm
  when: ansible_os_family == "Suse"

- name: Gather package facts
....
....
```

**Comment by berndfinger** [comment]
@sean-freeman We can safely assume that the package python3-rpm is present on RHEL, because:
- The [description of the module package_facts](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_facts_module.html) does not mention a specific requirement for RHEL or Fedora-based systems. 
- When installing RHEL 9.2 with the minimal_install software environment group, this package is installed.

For SLES based systems, the following task should also work and could avoid the use of the `command` module:
```
- name: Ensure package python3-rpm is present - required for package_facts module on SLES
  ansible.builtin.package:
    - python3-rpm
  when: ansible_os_family == "Suse"
```
