### ISSUE TITLE
sap_swpm: incorrect label in loop in swpm.yml

### ISSUE THREAD

**Issue by rnozaki** [sap-linuxlab/community.sap_install#681]
1. In the file swpm.yml, under the role sap_swpm one of the tasks is pointing to an incorrect name for a label in a loop_control.

```
- name: SAP SWPM - Display status from sapcontrol file/s
  ansible.builtin.debug:
    msg: "{{ ['GetInstanceProperties'] + file_output.stdout_lines }}"
  loop: "{{ swpm_sapcontrol_file_contents.results }}"
  loop_control:
    loop_var: file_output
    label: "{{ file_output.item }}"       # << This should be line_item, as this was added recently to a loop in a previous task
```

2. After I used the dev branch (from PR $665), I got the following error:

```
###
TASK [community.sap_install.sap_swpm : SAP SWPM - Display status from sapcontrol file/s] ***15:12:00
failed: [xxxxxx] (item=None) => {
"msg": "Failed to template loop_control.label: 'dict object' has no attribute 'item'"
}
fatal: [xxxxxx]: FAILED! => {"msg": "One or more items failed"}
```

3. I noticed that 2 tasks above there was a recent change adding the loop_var under loop_control.

4. So I updated the code:
a. From:  label: "{{ file_output.item }}"   
b. To:  label: "{{ file_output.line_item }}"

5. With this update, the playbook was re-executed without error.

**Comment by marcelmamula** [comment]
Did you check previous step in execution log that it registered that variable? It is possible it did not find any files, therefore item was not defined.

I have been running it in current state and I never had this issue with .item.

```
- name: SAP SWPM - Find sapcontrol log file/s
  ansible.builtin.find:
    paths: "{{ swpm_last_install_path.stdout }}"
    recurse: false
    file_type: file
    patterns: '.*sapcontrol.*log'
    use_regex: true
  register: swpm_output_sapcontrol_files
```

**Comment by berndfinger** [comment]
@rnozaki I had the same error when testing an S/4HANA Foundation 2022 installation last week but I could not finish my investigation. Trying to reproduce it again now and also testing the solution you proposed.

**Comment by rnozaki** [comment]
> Did you check previous step in execution log that it registered that variable? It is possible it did not find any files, therefore item was not defined.
> 
> I have been running it in current state and I never had this issue with .item.
> 
> ```
> - name: SAP SWPM - Find sapcontrol log file/s
>   ansible.builtin.find:
>     paths: "{{ swpm_last_install_path.stdout }}"
>     recurse: false
>     file_type: file
>     patterns: '.*sapcontrol.*log'
>     use_regex: true
>   register: swpm_output_sapcontrol_files
> ```

As I mentioned, I tested the new code with the exact same conditions it was working before.
And when I added the new label, it *found* the element.
So  in my case, just fixing the label solved the problem.

Have you executed this code in your environment?

**Comment by marcelmamula** [comment]
> > Did you check previous step in execution log that it registered that variable? It is possible it did not find any files, therefore item was not defined.
> > I have been running it in current state and I never had this issue with .item.
> > ```
> > - name: SAP SWPM - Find sapcontrol log file/s
> >   ansible.builtin.find:
> >     paths: "{{ swpm_last_install_path.stdout }}"
> >     recurse: false
> >     file_type: file
> >     patterns: '.*sapcontrol.*log'
> >     use_regex: true
> >   register: swpm_output_sapcontrol_files
> > ```
> 
> As I mentioned, I tested the new code with the exact same conditions it was working before. And when I added the new label, it _found_ the element. So in my case, just fixing the label solved the problem.
> 
> Have you executed this code in your environment?

That is why I was mentioning previous step. It would be good to know what was actual content of your "{{ swpm_output_sapcontrol_files }}" variable and if it contains array with items.

I have run this role 20+ times over last 2 weeks (ASCS/ERS, S4H, NW) and it never failed with this error, even if SWPM was successful or failed.

**Comment by marcelmamula** [comment]
Sorry @rnozaki  , it seems @berndfinger  moved his PR and it changed items as you said. I have not tested it with his PR. You can disregard my comments.

**Comment by berndfinger** [comment]
@rnozaki @marcelmamula In https://github.com/sap-linuxlab/community.sap_install/pull/665, I overlooked the fact that the loop variable from the task `SAP SWPM - Get sapcontrol file/s` is re-used for the label in the task `SAP SWPM - Display status from sapcontrol file/s`. 
Thanks for solving the problem @rnozaki!

**Comment by berndfinger** [comment]
Solved in #682.

**Comment by berndfinger** [comment]
FYI - Test playbook for those who want to reproduce the problem:
```
- name: junk
  hosts: localhost
  vars:
    dummy:
      - 'test1'
      - 'test2'

  gather_facts: no

  tasks:

    - name: Display the list
      ansible.builtin.debug:
        msg: "{{ dummy }}"
 
    - name: Run command and register output with new loop_var
      ansible.builtin.command: "echo {{ line_item }}" 
      register: output
      loop: "{{ dummy }}"
      loop_control:
        loop_var: line_item

    - name: Display output with correct loop label
      ansible.builtin.debug:
        msg: "{{ command_output.stdout_lines }}"
      loop: "{{ output.results }}"
      loop_control:
        loop_var: command_output
        label: "{{ command_output.line_item }}"

    - name: Display output with wrong loop label
      ansible.builtin.debug:
        msg: "{{ command_output.stdout_lines }}"
      loop: "{{ output.results }}"
      loop_control:
        loop_var: command_output
        label: "{{ command_output.item }}"
```
