### ISSUE TITLE
sap_swpm: advanced mode inifile inorect build

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#698]
I am currently testing sap_swpm advanced mode for a customer and ran into a few issues:

1. The ini file is created like this:
`Param=value` instead of `Param = Value` (watch the blank space)
hence the detection of the FQDN fails with this command (LOG)
```
TASK [community.sap_install.sap_swpm : SAP SWPM - Detect FQDN] *****************
ok: [aztests4] => {"changed": false, "cmd": "set -o pipefail && cat /tmp/ansible.zwp70fvuswpmconfig/inifile.params | grep NW_getFQDN.FQDN | awk '{ print $3 }'\n", "delta": "0:00:00.010112", "end": "2024-04-11 10:47:05.771258", "msg": "", "rc": 0, "start": "2024-04-11 10:47:05.761146", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
The original SAP inifiles have the blanks around `=`. The awk either needs to use `-F= '{print $2}'`  plus  squeezing blanks in the beginning and end of $2 (` | tr -d'  '`).

Solution: when creating inifiles from advanced templates ensure blanks around `=`or update the awk and other commands

required patch:
file: `roles/sap_swpm/tasks/swpm/swpm_inifile_generate_advanced_templates.yml
```
[...]
- name: SAP SWPM advanced_templates mode - Loop over the dictionary and output to file
  ansible.builtin.lineinfile:
    path: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    state: present
    insertafter: EOF
    line: "{{ item.key }} = {{ item.value }}"
  with_dict: "{{ sap_swpm_templates_install_dictionary[sap_swpm_templates_product_input]['sap_swpm_inifile_custom_values_dictionary'] }}"
  tags: sap_swpm_generate_inifile
[...]
```

2. The productid is still detected and overwritten by the following code:
file: `roles/sap_swpm/tasks/swpm/detect_variables.yml`
```
# Detect Product ID
- name: SAP SWPM - Detect Product ID
  ansible.builtin.command: |
    awk 'BEGIN{IGNORECASE=1;a=0}
      /Product ID/&&a==0{a=1; gsub ("#", ""); gsub ("\047", ""); product_id=$NF}
      END{print product_id}' {{ sap_swpm_tmpdir.path }}/inifile.params
  register: sap_swpm_inifile_product_id_detect
  changed_when: false

# Set fact for product id
- name: SAP SWPM - Set SAP product ID
  ansible.builtin.set_fact:
    sap_swpm_product_catalog_id: "{{ sap_swpm_inifile_product_id_detect.stdout }}"
```
