### ISSUE TITLE
sap_swpm: Argument list can be too long when setting file permissions

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#721]
In the task https://github.com/sap-linuxlab/community.sap_install/blob/4636753597d67619e8e06091052dcb7b23e5ebc1/roles/sap_swpm/tasks/swpm/prepare_software.yml#L72, the error `[Errno 7] Argument list too long: '/bin/sh'` can occur if there are a lot of files (e.g. more than 683) in the __sap_swpm_fact_files_non_sapcar_chown_arg_list. This can happen if there are directories with many extracted files in `sap_swpm_software_path`, e.g. from a previous installation.

Workaround: Skip setting file permissions and ownership by setting role parameter `sap_swpm_set_file_permissions` to `false`, or ensure there are no directories in `sap_swpm_software_path` with files which are not needed for the SWPM installation.

See also https://github.com/sap-linuxlab/community.sap_install/issues/663.

**Comment by berndfinger** [comment]
We could just skip all the `*extracted*` directories when setting file permissions and ownership. At the time when the file and directory permissions are set by the role, permissions and ownership only of files which are not already extracted will have to be modified.

**Comment by marcelmamula** [comment]
@berndfinger I would suggest different approach. It is easier to create batches of 100 files and run them in loop.

This is short example I made for test, which splits into batches of 3:
```yaml
  vars:
    file_input: "fileA fileB fileC fileD fileE fileF fileG fileX"
  tasks:
    - name: Assign file_input into file_list
      ansible.builtin.set_fact:
        file_list: "{{ file_input.split(' ') }}"

    - name: Show file_list in loop per batch
      ansible.builtin.debug:
        msg: "{{ item | join(' ') }}"
      loop: "{{ file_list | batch(3) }}"
      loop_control:
        label: "Batch {{ (file_list.index(item[0]) // 3) + 1 }}"
```

```console
TASK [Show file_list in loop per batch] *********************************************************************************************************************
ok: [localhost] => (item=Batch 1) => {
    "msg": "fileA fileB fileC"
}
ok: [localhost] => (item=Batch 2) => {
    "msg": "fileD fileE fileF"
}
ok: [localhost] => (item=Batch 3) => {
    "msg": "fileG fileX"
}
```
