### ISSUE TITLE
sap_swpm: add (pseudo)idempotency 

### ISSUE THREAD

**Issue by rob0d** [sap-linuxlab/community.sap_install#730]
It seems that SWPM in an unattended mode happily overwrites already installed systems. We've just experienced this when we executed the full workflow on a partially installed environment and it reinstalled one of the instances (and remove all the configuration that was done to that instance).

I would like to suggest to make `sap_swpm`  idempotent (dependant on settings). 

The safest and simplest way to do this would be probably to check the existence of an instance profile. This can be done either generating the file name from the parameters that are set or  by using code from [sap_profile_update](https://github.com/sap-linuxlab/community.sap_operations/blob/e247f47e7172c7f9e48c2bc87ea466b7a4ce1e47/roles/sap_profile_update/tasks/main.yml#L3C1-L7C8).

There would be three possible behaviours:
 - default: as is now and just execute SWPM and overwrite any existing instances
 - if instance already exists:
   - throw error
   - skip installation but continue
  
This can be  achieved by having something like  `sap_swpm_check_if_instance_exists ` with options:
- `false` to keep the current behaviour (default)
- `error` to throw error
- `ignore` to ignore it and continue

I guess similar outcome can be achieved by splitting playbooks into smaller chunks and manually re-executing the failed bits if something goes wrong with one of the workflow steps, but that feels error prone and user dependent.

**Comment by marcelmamula** [comment]
@rob0d We will be implementing validations in sap_install roles some time in future to achieve this. @sean-freeman 
There are already some ways we handle it during our tests and developments, which we can ten transfer to actual roles.

I am for example using this idempotency to detect and skip:
- hana install, hsr replication
- ascs, ers, pas, aap installed

Issue is of course caused by SWPM, which will blast home folder of sidadm user, then fail on subsequent steps after it finds kernel files already present.

**Comment by rob0d** [comment]
@marcelmamula that would be good. I can probably test some of it if it's available in the next month or so.
I think check in /usr/sap/sapservice and/or instance profile is probably the safest way of determining if something is (supposedly) installed without changing the state of anything.
And yes, the only way to prevent SWPM from updating the user profiles is not to start it at all.

**Comment by marcelmamula** [comment]
`sap_hana_install` role already contains check for HANA existence and I think it can be partially reused to enhance `sap_swpm` role to not destroy system during re-executions.
- check for existence of SAP processes / executables
- if exists, then use them for SID + InstNR check
- if not exists, then check `/etc/passwd` for sidadm user, `/sapmnt/SID/profile/<profile>` existence, etc.

https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_install/tasks/hana_exists.yml

@berndfinger

**Comment by rob0d** [comment]
@marcelmamula  do you have any detection code for HSR that you can share? I am doing loads of HANA cluster (re)installs and was going to write something. However, if you have it already I can test it.

Also I wrote SAP system detection which can skip SWPM, but made it slightly different with several different checks which return how probable is that SAP is actually installed (returning score 1-5 with 5 meaning almost certainly installed and working). We can't rely just on host agent or sapservice. Sap_system_facts is a good idea, but it will be accurate only if the system is in a consistent state, which may not be the case if you are trying to repeatedly reinstall things.

**Comment by marcelmamula** [comment]
@rob0d My custom playbooks have HSR idempotency as well, with following code.

- I check profile existence before hana install so I can skip it
- I check it after install as well
- Followed by attempt to start HANA, because replication check needs it running
- Verify replication

```yaml
    - name: Attempt to start HANA
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_system_hana_db_sid | upper }}/home/.sapenv.sh && \
        HDB start
      become: true
      become_user: "{{ sidadm_hana }}"
      changed_when: false
      failed_when: false

    - name: Verify if HSR replication is enabled
      ansible.builtin.shell: |
        source /usr/sap/{{ sap_system_hana_db_sid | upper }}/home/.sapenv.sh && \
        /usr/sap/{{ sap_system_hana_db_sid | upper }}/HDB{{ sap_system_hana_db_instance_nr }}/exe/hdbnsutil \
        -sr_state
      become: true
      become_user: "{{ sidadm_hana }}"
      register: sap_hana_hsr_srstate
      changed_when: false
      failed_when: false

    - name: Execute Ansible Role sap_ha_install_hana_hsr
      ansible.builtin.include_role:
        name: community.sap_install.sap_ha_install_hana_hsr
      vars:
        sap_ha_install_hana_hsr_cluster_nodes: "{{ sap_hana_cluster_nodes }}"
      when: ansible_hostname not in sap_hana_hsr_srstate.stdout
```
