### ISSUE TITLE
sap_swpm: sap_swpm_install_software_extract_directory missing

### ISSUE THREAD

**Issue by surajsbharadwaj** [sap-linuxlab/community.sap_install#741]
**sap_swpm**

 The role runs into an error when the software is in the **NFS** folder.
 
  `sap_hana_install` role has a similar parameter which extracts the binaries to a user defined location using `sap_hana_install_software_extract_directory` and avoids the issue.

Can you enable a new parameter **`sap_swpm_install_software_extract_directory`**?

```yaml
TASK [redhat.sap_install.sap_swpm : SAP SWPM Pre Install - Change ownership of software path - /software/S4HANA_2022] ***

 fatal: [10.51.0.240]: FAILED! =>
  {
      "changed": false,
      "gid": 65534,
      "group": "nobody",
      "mode": "0777",
      "msg": "chown failed: [Errno 1] Operation not permitted: b'/software/S4HANA_2022'",
      "owner": "nobody",
      "path": "/software/S4HANA_2022",
      "secontext": "system_u:object_r:nfs_t:s0",
      "size": 4096,
      "state": "directory",
      "uid": 65534
  }
```
