### ISSUE TITLE
sap_ha_pacemaker_cluster/SLES: add the installation of necessary Python packages to prepare for #720.

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#753]
Certain packages which have been installed in the role `sap_swpm` were a requirement for running `sap_ha_pacemaker_cluster` on SLES, see https://github.com/sap-linuxlab/community.sap_install/pull/720#pullrequestreview-2103850795. With PR #720, these packages will no longer be installed. So the installation of these packages now has to be done in the role(s) which demand it.

Related code in role `sap_swpm` is:
```
# Required for Ansible Module pids
- name: Install Python devel, Python pip and gcc to system Python
  ansible.builtin.package:
    name:
      - python3-devel
      - python3-pip
      - gcc
    state: present

# Required for Ansible Module pids
- name: Install Python dependency psutil to system Python
  ansible.builtin.pip:
    name:
      - psutil
```
