### ISSUE TITLE
sap_hana_install : SAP HANA Checks - Fail if the user 'sidadm' exists

### ISSUE THREAD

**Issue by jaaphellemons82** [sap-linuxlab/community.sap_install#787]
We are using the sap_hana_install role and as part of our deployment pipeline we create sidadm users before running this playbook. THe installation fails due to the following task:

```
    - name: SAP HANA Checks - Fail if the user '{{ sap_hana_install_sid | lower }}adm' exists
      ansible.builtin.fail:
        msg: "FAIL: User '{{ sap_hana_install_sid | lower }}adm' exists!"
      when: __sap_hana_install_register_getent_passwd_sidadm.rc == 0
```
which is part of roles/sap_hana_install/tasks/hana_exists.yml

I am not sure why this check is done, since it is fully supported by SAP to have the sidadm user created before the installation starts. Please see the official installation guide from SAP: 

https://help.sap.com/docs/SAP_HANA_PLATFORM/2c1988d620e04368aa4103bf26f17727/1dbba6ac03054d7eb07c819aae47d095.html#loio3c831ee47beb4499972774f4a080d1d3

![image](https://github.com/sap-linuxlab/community.sap_install/assets/152391194/d56d21b1-9ccb-448e-a830-4ae7b0413e5b)
