### ISSUE TITLE
sap_storage_setup: README.MD example is wrong, please fix it.

### ISSUE THREAD

**Issue by herrmie** [sap-linuxlab/community.sap_install#798]
Hello,
the example in the role is wrong for the parameter disk_size and filesystem_type.

- For disk_size the G at the end need to be removed
- For filesystem_type it says the default is xfs, if I don't define parameter filesystem_type it is not working.

```
sap_storage_setup_definition:
- disk_size: 100
  filesystem_type: xfs
  mountpoint: /hana/data
  name: hanadata
- disk_size: 100
  filesystem_type: xfs
  mountpoint: /hana/log
  name: hanalog
```

Best regards,
Steffen Herrmann
