### ISSUE TITLE
sap_hana_install: Run the hdbuserstore command via su from superuser

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#847]
When running the `sap_hana_install` role using a non-root user, the task `Create and Store Connection Info in hdbuserstore` fails with `Missing sudo password` if the credentials for connecting to the `<sid>adm` user have not been provided before, because the task is running with `<sid>adm` as the `become_user`.

This can be avoided by calling the `hdbuserstore` command via `su` from the `<sid>adm` user.

**Comment by marcelmamula** [comment]
@berndfinger Look at solution in https://github.com/sap-linuxlab/community.sap_install/pull/1214
You cannot run some commands from non-root even with `visudo` configured. Same goes with this issue, because you cannot run paswordless `su` without `visudo`.

```yaml
# Using non-root user requires additional package 'acl' to be present.
# This is required when non-root user with sudo needs to become other non-root user.
- name: SAP Host Agent - SSL - Ensure ACL is installed for non-root user to enable become to 'sapadm' user
  ansible.builtin.package:
    name: acl
    state: present
  become: true
  # User 'root' is hardcoded as UUID 0 and it does not require 'acl' package.
  when: ansible_facts['user_uid'] != 0
```
